import type { Place } from '@/types'

export const places: Place[] = [
  {
    id: '1',
    slug: 'adobe-guadalupe',
    name_en: 'Adobe Guadalupe',
    name_es: 'Adobe Guadalupe',
    description_en: 'A stunning boutique winery and inn nestled in the heart of Valle de Guadalupe. Known for its exceptional Bordeaux-style blends, beautiful gardens, and world-class hospitality. The perfect place to experience Baja California wine country at its finest.',
    description_es: 'Una impresionante bodega boutique y posada en el corazón del Valle de Guadalupe. Conocida por sus excepcionales mezclas estilo Burdeos, hermosos jardines y hospitalidad de clase mundial.',
    category: 'winery',
    tags: ['luxury', 'romantic', 'tasting_room', 'outdoor'],
    address: 'Parcela 72-A, Valle de Guadalupe, Ensenada, B.C.',
    lat: 32.0853,
    lng: -116.6013,
    phone: '+52 646 155 2094',
    whatsapp: '526461552094',
    website: 'https://adobeguadalupe.com',
    instagram: 'https://instagram.com/adobeguadalupe',
    opentable_url: null,
    hours: {
      monday: 'Closed',
      tuesday: '10:00 AM - 5:00 PM',
      wednesday: '10:00 AM - 5:00 PM',
      thursday: '10:00 AM - 5:00 PM',
      friday: '10:00 AM - 6:00 PM',
      saturday: '9:00 AM - 6:00 PM',
      sunday: '9:00 AM - 5:00 PM',
    },
    price_range: 3,
    images: [],
    featured: true,
    active: true,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: '2',
    slug: 'fauna-restaurant',
    name_en: 'Fauna Restaurant',
    name_es: 'Restaurante Fauna',
    description_en: 'Award-winning farm-to-table restaurant located within the Bruma winery estate. Chef David Castro Hussong creates extraordinary tasting menus that celebrate the flavors of Baja California using locally sourced ingredients.',
    description_es: 'Restaurante de campo a mesa galardonado ubicado en el viñedo Bruma. El chef David Castro Hussong crea extraordinarios menús de degustación que celebran los sabores de Baja California.',
    category: 'restaurant',
    tags: ['luxury', 'romantic', 'outdoor'],
    address: 'Bruma Estate, Valle de Guadalupe, Ensenada, B.C.',
    lat: 32.0901,
    lng: -116.5987,
    phone: '+52 646 156 8008',
    whatsapp: '526461568008',
    website: 'https://faunarestaurant.com',
    instagram: 'https://instagram.com/faunarestaurant',
    opentable_url: 'https://opentable.com/fauna',
    hours: {
      monday: 'Closed',
      tuesday: 'Closed',
      wednesday: '1:00 PM - 10:00 PM',
      thursday: '1:00 PM - 10:00 PM',
      friday: '1:00 PM - 11:00 PM',
      saturday: '12:00 PM - 11:00 PM',
      sunday: '12:00 PM - 9:00 PM',
    },
    price_range: 4,
    images: [],
    featured: true,
    active: true,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: '3',
    slug: 'encuentro-guadalupe',
    name_en: 'Encuentro Guadalupe',
    name_es: 'Encuentro Guadalupe',
    description_en: 'An iconic eco-resort perched on the hillside overlooking the Valle de Guadalupe. Features unique floating cabins with panoramic views of the vineyards. An unforgettable glamping experience in wine country.',
    description_es: 'Un icónico eco-resort en la ladera con vista al Valle de Guadalupe. Cabañas flotantes únicas con vistas panorámicas de los viñedos.',
    category: 'hotel',
    tags: ['luxury', 'romantic', 'outdoor'],
    address: 'Km 75 Carr. Tecate-Ensenada, Valle de Guadalupe, B.C.',
    lat: 32.0756,
    lng: -116.6102,
    phone: '+52 646 155 2775',
    whatsapp: '526461552775',
    website: 'https://encuentroguadalupe.com',
    instagram: 'https://instagram.com/encuentroguadalupe',
    opentable_url: null,
    hours: {
      monday: '24 hours',
      tuesday: '24 hours',
      wednesday: '24 hours',
      thursday: '24 hours',
      friday: '24 hours',
      saturday: '24 hours',
      sunday: '24 hours',
    },
    price_range: 4,
    images: [],
    featured: true,
    active: true,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: '4',
    slug: 'vena-cava',
    name_en: 'Vena Cava Winery',
    name_es: 'Vena Cava',
    description_en: 'One of the most creative and unique wineries in Baja California. Built from repurposed boats and materials, Vena Cava offers a truly one-of-a-kind tasting experience with wines that reflect the wild spirit of the valley.',
    description_es: 'Una de las bodegas más creativas de Baja California. Construida con botes reciclados, ofrece una experiencia de cata verdaderamente única.',
    category: 'winery',
    tags: ['tasting_room', 'outdoor', 'live_music'],
    address: 'Rancho San Marcos, Valle de Guadalupe, Ensenada, B.C.',
    lat: 32.0821,
    lng: -116.5934,
    phone: '+52 646 156 8054',
    whatsapp: '526461568054',
    website: 'https://venacava.com',
    instagram: 'https://instagram.com/venacavawine',
    opentable_url: null,
    hours: {
      monday: 'Closed',
      tuesday: 'Closed',
      wednesday: '11:00 AM - 5:00 PM',
      thursday: '11:00 AM - 5:00 PM',
      friday: '11:00 AM - 6:00 PM',
      saturday: '10:00 AM - 6:00 PM',
      sunday: '10:00 AM - 5:00 PM',
    },
    price_range: 2,
    images: [],
    featured: false,
    active: true,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: '5',
    slug: 'corazon-de-tierra',
    name_en: 'Corazón de Tierra',
    name_es: 'Corazón de Tierra',
    description_en: 'A celebrated farm-to-table restaurant surrounded by organic gardens and vineyards. Chef Diego Hernández crafts seasonal menus that have earned international recognition and put Valle de Guadalupe on the global culinary map.',
    description_es: 'Restaurante de campo a mesa rodeado de jardines orgánicos y viñedos. El chef Diego Hernández crea menús de temporada de reconocimiento internacional.',
    category: 'restaurant',
    tags: ['luxury', 'outdoor', 'romantic'],
    address: 'Rancho San Marcos KM 93, Valle de Guadalupe, B.C.',
    lat: 32.0834,
    lng: -116.6078,
    phone: '+52 646 156 8030',
    whatsapp: '526461568030',
    website: 'https://corazondetierra.com',
    instagram: 'https://instagram.com/corazondetierra',
    opentable_url: 'https://opentable.com/corazon-de-tierra',
    hours: {
      monday: 'Closed',
      tuesday: 'Closed',
      wednesday: '1:00 PM - 9:00 PM',
      thursday: '1:00 PM - 9:00 PM',
      friday: '1:00 PM - 10:00 PM',
      saturday: '12:00 PM - 10:00 PM',
      sunday: '12:00 PM - 8:00 PM',
    },
    price_range: 4,
    images: [],
    featured: false,
    active: true,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: '6',
    slug: 'hacienda-guadalupe',
    name_en: 'Hacienda Guadalupe',
    name_es: 'Hacienda Guadalupe',
    description_en: 'A charming boutique hotel and winery offering comfortable rooms, excellent wines, and a relaxed atmosphere. Perfect for travelers looking for an authentic wine country experience without the luxury price tag.',
    description_es: 'Hotel boutique y bodega con habitaciones cómodas, excelentes vinos y ambiente relajado. Perfecto para viajeros que buscan autenticidad.',
    category: 'hotel',
    tags: ['tasting_room', 'pet_friendly', 'outdoor'],
    address: 'Carretera Ensenada-Tecate Km 81.3, Valle de Guadalupe, B.C.',
    lat: 32.0789,
    lng: -116.5956,
    phone: '+52 646 155 2859',
    whatsapp: '526461552859',
    website: 'https://haciendaguadalupe.com',
    instagram: 'https://instagram.com/haciendaguadalupe',
    opentable_url: null,
    hours: {
      monday: '24 hours',
      tuesday: '24 hours',
      wednesday: '24 hours',
      thursday: '24 hours',
      friday: '24 hours',
      saturday: '24 hours',
      sunday: '24 hours',
    },
    price_range: 2,
    images: [],
    featured: false,
    active: true,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: '7',
    slug: 'baja-wine-tours',
    name_en: 'Baja Wine Tours',
    name_es: 'Baja Wine Tours',
    description_en: 'The premier wine tour operator in Valle de Guadalupe. Offering guided tours to the best wineries, transportation from San Diego and Tijuana, and customized experiences for groups and couples.',
    description_es: 'El principal operador de tours de vino en Valle de Guadalupe. Tours guiados, transporte desde San Diego y Tijuana, y experiencias personalizadas.',
    category: 'tour',
    tags: ['family', 'pet_friendly'],
    address: 'Valle de Guadalupe, Ensenada, B.C.',
    lat: 32.0853,
    lng: -116.6013,
    phone: '+52 646 178 3201',
    whatsapp: '526461783201',
    website: 'https://bajawinetours.com',
    instagram: 'https://instagram.com/bajawinetours',
    opentable_url: null,
    hours: {
      monday: '8:00 AM - 6:00 PM',
      tuesday: '8:00 AM - 6:00 PM',
      wednesday: '8:00 AM - 6:00 PM',
      thursday: '8:00 AM - 6:00 PM',
      friday: '8:00 AM - 7:00 PM',
      saturday: '7:00 AM - 7:00 PM',
      sunday: '7:00 AM - 6:00 PM',
    },
    price_range: 2,
    images: [],
    featured: false,
    active: true,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: '8',
    slug: 'spa-del-valle',
    name_en: 'Spa del Valle',
    name_es: 'Spa del Valle',
    description_en: 'A luxurious wellness retreat offering wine-based treatments, massages, and holistic therapies inspired by the valley\'s natural ingredients. The perfect complement to a wine country getaway.',
    description_es: 'Un lujoso retiro de bienestar con tratamientos a base de vino, masajes y terapias holísticas inspiradas en los ingredientes naturales del valle.',
    category: 'spa',
    tags: ['luxury', 'romantic'],
    address: 'Valle de Guadalupe, Ensenada, B.C.',
    lat: 32.0867,
    lng: -116.5998,
    phone: '+52 646 178 4502',
    whatsapp: '526461784502',
    website: 'https://spadelvalle.com',
    instagram: 'https://instagram.com/spadelvalle',
    opentable_url: null,
    hours: {
      monday: 'Closed',
      tuesday: '10:00 AM - 6:00 PM',
      wednesday: '10:00 AM - 6:00 PM',
      thursday: '10:00 AM - 6:00 PM',
      friday: '10:00 AM - 7:00 PM',
      saturday: '9:00 AM - 7:00 PM',
      sunday: '9:00 AM - 6:00 PM',
    },
    price_range: 3,
    images: [],
    featured: false,
    active: true,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
  id: '9',
  slug: 'cuatro-cuatros',
  name_en: 'Cuatro Cuatros',
  name_es: 'Cuatro Cuatros',
  description_en: 'A world-class resort and winery complex nestled between the vineyards of Valle de Guadalupe and the Pacific Ocean. Cuatro Cuatros offers boutique hotel rooms and cabins, three exceptional restaurants — Arsénico, Tahona and Bura — private wine tastings, spa, heated pool, and unforgettable experiences including sailing, helicopter tours, horseback riding, zip-lines and hiking. The ultimate Baja California escape.',
  description_es: 'Un complejo turístico y vinícola de clase mundial entre los viñedos del Valle de Guadalupe y el Océano Pacífico. Cuatro Cuatros ofrece hotel boutique, cabañas, tres restaurantes excepcionales — Arsénico, Tahona y Bura — degustaciones de vino, spa, alberca climatizada y experiencias inolvidables como paseos en velero, helicóptero, cabalgatas, tirolesas y senderismo.',
  category: 'hotel',
  tags: ['luxury', 'romantic', 'outdoor', 'tasting_room', 'wedding_venue', 'pet_friendly'],
  address: 'Carretera Ensenada-Tijuana Km 88, Valle de Guadalupe, Ensenada, B.C.',
  lat: 32.0412,
  lng: -116.6891,
  phone: '+52 646 178 3780',
  whatsapp: '526461783780',
  website: 'https://cuatrocuatros.com',
  instagram: 'https://instagram.com/cuatrocuatrosmx',
  opentable_url: null,
  hours: {
    monday: '8:00 AM - 10:00 PM',
    tuesday: '8:00 AM - 10:00 PM',
    wednesday: '8:00 AM - 10:00 PM',
    thursday: '8:00 AM - 10:00 PM',
    friday: '8:00 AM - 11:00 PM',
    saturday: '7:00 AM - 11:00 PM',
    sunday: '7:00 AM - 10:00 PM',
  },
  price_range: 4,
  images: [],
  featured: true,
  active: true,
  created_at: '2026-01-01T00:00:00Z',
},
]

export const getFeaturedPlaces = () => places.filter(p => p.featured)
export const getPlaceBySlug = (slug: string) => places.find(p => p.slug === slug)
export const getPlacesByCategory = (category: string) => places.filter(p => p.category === category)